Added automatic push of maven artifacts on master and develop
samply/common-http pull request #4
Opened 2021-08-24 11:47 UTC by torbrenner

**What's in the PR**
* extension of the ci workflow for signing and deploying the maven artifact

You can view the automatically created artifacts at [oss.sonatype.org](https://oss.sonatype.org/index.html#view-repositories;snapshots~browsestorage~/de/samply/common-http/7.3.0-SNAPSHOT/common-http-7.3.0-20210824.112749-1.jar).
Currently the files are signed with my account. I would try to create a bot account at sonatype for samply.

** Please Note **
* changes to the pom.xml should be pushed to samply parent. I will create a PR and link it.

2021-08-24 12:07 UTC, torbrenner commented
Created the PR for samply.parent: https://github.com/samply/maven-parent/pull/5

2021-08-25 13:01 UTC, alexanderkiel requested changes

2021-08-25 13:01 UTC, alexanderkiel commented on .github/workflows/ci.yml
> +    - name: Run the unit tests
I would introduce a line break before each step to improve readability.

2021-08-25 13:40 UTC, alexanderkiel approved these changes

2021-08-25 13:43 UTC, merged